# Generated by Django 5.2.9 on 2026-01-10 06:51

from django.db import migrations


def fill_construction_year_field(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.construction_year >= 2015:
            flat.new_building == True
        else:
            flat.new_building == False


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_construction_year_field),
    ]
