# Generated by Django 5.2.9 on 2026-01-10 07:19

from django.db import migrations


def fill_construction_year_field(app, schema_editor):
    Flat = app.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)
    Flat.objects.filter(construction_year__lt=2015).update(new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20260110_0951'),
    ]

    operations = [
        migrations.RunPython(fill_construction_year_field),
    ]
