# Generated by Django 5.2.9 on 2026-01-14 11:25

from django.db import migrations

import phonenumbers


def normalize_phone_number(old_number):
    try:
        parsed_number = phonenumbers.parse(old_number, 'RU')
    except phonenumbers.NumberParseException:
        return None

    if phonenumbers.is_valid_number(parsed_number):
        normalize_number = phonenumbers.format_number(
            parsed_number,
            phonenumbers.PhoneNumberFormat.E164,
        )
    else:
        normalize_number = None

    return normalize_number


def normalization_of_phone_numbers(app, shema_editor):
    Flat = app.get_model('property', 'Flat')
    flats = Flat.objects.filter(owners_phonenumber='+70000000000')

    for flat in flats:
        normalized = normalize_phone_number(flat.owners_phonenumber)
        flat.owner_pure_phone = normalized
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_alter_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(normalization_of_phone_numbers)
    ]
