# Generated by Django 5.2.9 on 2026-01-18 07:47

from django.db import migrations


def transfer_of_ownership(app, shema_editor):
    Flat = app.get_model('property', 'Flat')
    Owner = app.get_model('property', 'Owner')
    flats = Flat.objects.all()
    
    for flat in flats:
        Owner.objects.get_or_create(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owners_pure_phone=flat.owner_pure_phone,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_owner'),
    ]

    operations = [
        migrations.RunPython(transfer_of_ownership)
    ]
