# Generated by Django 5.2.9 on 2026-01-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_alter_owner_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owners_flats',
            field=models.ManyToManyField(blank=True, related_name='owners_flats', to='property.flat', verbose_name='Квартиры в собственности'),
        ),
    ]
