# Generated by Django 5.2.9 on 2026-01-18 15:37

from django.db import migrations


def create_owner_flat_connections(app, shema_editor):
    Flat = app.get_model('property', 'Flat')
    Owner = app.get_model('property', 'Owner')

    owners = Owner.objects.all()

    for owner in owners:
        flat = Flat.objects.filter(owner=owner.owner)
        owner.owners_flats.set(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_alter_owner_owners_flats'),
    ]

    operations = [
    ]
