# Generated by Django 5.2.9 on 2026-01-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20260118_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owners_flats',
            field=models.ManyToManyField(blank=True, related_name='flat_owners', to='property.flat', verbose_name='Квартиры в собственности'),
        ),
    ]
